### ISSUE TITLE
Migration example

### ISSUE THREAD

**Issue by slipset** [y42/clj-druid#15]
I'm currently using cli-druid version 0.2.12, which lets me connect by calling

```clojure
(let [zk-client (zk/connect "zk1,zk2,zk3")]
   (druid\zk-watch-node-list zk-client "/druid/discovery/druid:broker"))
```
Which suits me quite well, since I'm using the zookeeper client for other stuff as well.

How would this be done in 0.2.16?

**Comment by msprunck** [comment]
In 0.2.16 clj-druid uses [Curator](http://curator.apache.org/curator-client/index.html) to discover Druid nodes. Druid itself uses the Curator client to announces its nodes.

To connect, you have just to use the following code:

```
(druid/connect {:zk {:host "zk1,zk2,zk3"
                     :discovery-path "/druid/discovery"
                     :node-type "broker"}})
```
