### ISSUE TITLE
Wrong node-type in connect-with-zk docs

### ISSUE THREAD

**Issue by slipset** [y42/clj-druid#17]
Doc states:

```clojure
(connect {:zk {:host "127.0.0.1:2181,my-other-zk-host:2181" ; can contain multiple hosts separated by commas
               :discovery-path "/druid/discovery"
               :node-type "broker"}})
```

At least in my environment, this should be 

```clojure
(connect {:zk {:host "127.0.0.1:2181,my-other-zk-host:2181" ; can contain multiple hosts separated by commas
               :discovery-path "/druid/discovery"
               :node-type "druid:broker"}})
```

**Comment by msprunck** [comment]
The `:node-type` is defined by each Druid node in the configuration file with the `druid.service` property (by default its value is `druid/broker`). The character `/` is replaced by `:`.

**Comment by slipset** [comment]
My problem was that in my environment trying to connect with 

``` clojure
(connect {:zk {:host "127.0.0.1:2181,my-other-zk-host:2181" ; can contain multiple hosts separated by commas
               :discovery-path "/druid/discovery"
               :node-type "broker"}})
```

gave me an error indicating that druid could not be found.
After digging around a bit, I found that zookeeper exposed this as `druid:broker`, hence the issue.

If this is just an artefact of our setup, please disregard this issue.

**Comment by msprunck** [comment]
The value `druid:broker` matches the default configuration of Druid. It is better to show an example with the default configuration.
